targets:
  - index: 1
    position: [0.0, 15.0]
    time_window: 1000
  - index: 2
    position: [15.0, 0.0]
    time_window: 1000
  - index: 3
    position: [-15.0, 0.0]
    time_window: 1000

charge_stations:
  - index: A
    position: [0.0, 10.0]
  - index: B
    position: [10.0, 0.0]
  - index: C
    position: [ -10.0, 0.0 ]
  - index: D
    position: [ 0.0, 0.0 ]
